### ISSUE TITLE
dcp_tool diversifier

### ISSUE THREAD

**Issue by OmarAberkan** [inversepath/mxs-dcp#1]
The dcp_tool requires a diversifier as a parameter.
What is this "diversifier" and can you give an example on how to use it?

**Comment by andrejro** [comment]
The "diversifier" parameter is used to obtain key diversification: the encryption is done via a key derived from the single per-device OTPMK key, the "diversifier" parameter allows to have multiple keys (256) derived from the same OTPMK key.
Check https://en.wikipedia.org/wiki/Key_derivation_function

**Comment by OmarAberkan** [comment]
Should't this be optional then?
